//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaIntegracion.CoreServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebServicesCore.core/", ConfigurationName="CoreServices.WebServicesCoreSoap")]
    public interface WebServicesCoreSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Consulta_de_balance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaIntegracion.CoreServices.Response Consulta_de_balance(string Cedula, string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Consulta_de_balance", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Consulta_de_balanceAsync(string Cedula, string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Depositar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaIntegracion.CoreServices.Response Depositar(string Cedula, string Cuenta, decimal Monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Depositar", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> DepositarAsync(string Cedula, string Cuenta, decimal Monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Mostrar_cuentas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaIntegracion.CoreServices.Response Mostrar_cuentas(string Cedula, string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Mostrar_cuentas", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Mostrar_cuentasAsync(string Cedula, string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Mostrar_cuentas_del_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaIntegracion.CoreServices.Response Mostrar_cuentas_del_cliente(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Mostrar_cuentas_del_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Mostrar_cuentas_del_clienteAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Movimiento_cuentas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaIntegracion.CoreServices.Response Movimiento_cuentas(string Cedula, string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Movimiento_cuentas", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Movimiento_cuentasAsync(string Cedula, string Cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Retirar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaIntegracion.CoreServices.Response Retirar(string Cedula, string Cuenta, decimal Monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Retirar", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> RetirarAsync(string Cedula, string Cuenta, decimal Monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Tiene_cuenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaIntegracion.CoreServices.Response Tiene_cuenta(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServicesCore.core/Tiene_cuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Tiene_cuentaAsync(string cedula);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebServicesCore.core/")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombre_completo_solicitanteField;
        
        private string cedulaField;
        
        private string mensajeField;
        
        private decimal montoField;
        
        private int validarField;
        
        private System.Data.DataTable dataTableField;
        
        private bool tiene_cuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre_completo_solicitante {
            get {
                return this.nombre_completo_solicitanteField;
            }
            set {
                this.nombre_completo_solicitanteField = value;
                this.RaisePropertyChanged("Nombre_completo_solicitante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
                this.RaisePropertyChanged("Cedula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("Monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int validar {
            get {
                return this.validarField;
            }
            set {
                this.validarField = value;
                this.RaisePropertyChanged("validar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Data.DataTable DataTable {
            get {
                return this.dataTableField;
            }
            set {
                this.dataTableField = value;
                this.RaisePropertyChanged("DataTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool tiene_cuenta {
            get {
                return this.tiene_cuentaField;
            }
            set {
                this.tiene_cuentaField = value;
                this.RaisePropertyChanged("tiene_cuenta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicesCoreSoapChannel : CapaIntegracion.CoreServices.WebServicesCoreSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicesCoreSoapClient : System.ServiceModel.ClientBase<CapaIntegracion.CoreServices.WebServicesCoreSoap>, CapaIntegracion.CoreServices.WebServicesCoreSoap {
        
        public WebServicesCoreSoapClient() {
        }
        
        public WebServicesCoreSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicesCoreSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesCoreSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesCoreSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaIntegracion.CoreServices.Response Consulta_de_balance(string Cedula, string Cuenta) {
            return base.Channel.Consulta_de_balance(Cedula, Cuenta);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Consulta_de_balanceAsync(string Cedula, string Cuenta) {
            return base.Channel.Consulta_de_balanceAsync(Cedula, Cuenta);
        }
        
        public CapaIntegracion.CoreServices.Response Depositar(string Cedula, string Cuenta, decimal Monto) {
            return base.Channel.Depositar(Cedula, Cuenta, Monto);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> DepositarAsync(string Cedula, string Cuenta, decimal Monto) {
            return base.Channel.DepositarAsync(Cedula, Cuenta, Monto);
        }
        
        public CapaIntegracion.CoreServices.Response Mostrar_cuentas(string Cedula, string Cuenta) {
            return base.Channel.Mostrar_cuentas(Cedula, Cuenta);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Mostrar_cuentasAsync(string Cedula, string Cuenta) {
            return base.Channel.Mostrar_cuentasAsync(Cedula, Cuenta);
        }
        
        public CapaIntegracion.CoreServices.Response Mostrar_cuentas_del_cliente(string Cedula) {
            return base.Channel.Mostrar_cuentas_del_cliente(Cedula);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Mostrar_cuentas_del_clienteAsync(string Cedula) {
            return base.Channel.Mostrar_cuentas_del_clienteAsync(Cedula);
        }
        
        public CapaIntegracion.CoreServices.Response Movimiento_cuentas(string Cedula, string Cuenta) {
            return base.Channel.Movimiento_cuentas(Cedula, Cuenta);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Movimiento_cuentasAsync(string Cedula, string Cuenta) {
            return base.Channel.Movimiento_cuentasAsync(Cedula, Cuenta);
        }
        
        public CapaIntegracion.CoreServices.Response Retirar(string Cedula, string Cuenta, decimal Monto) {
            return base.Channel.Retirar(Cedula, Cuenta, Monto);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> RetirarAsync(string Cedula, string Cuenta, decimal Monto) {
            return base.Channel.RetirarAsync(Cedula, Cuenta, Monto);
        }
        
        public CapaIntegracion.CoreServices.Response Tiene_cuenta(string cedula) {
            return base.Channel.Tiene_cuenta(cedula);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.CoreServices.Response> Tiene_cuentaAsync(string cedula) {
            return base.Channel.Tiene_cuentaAsync(cedula);
        }
    }
}
