//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaIntegracion.integracion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseHeader", Namespace="https://capaintegracionbanco.azurewebsites.net")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CapaIntegracion.integracion.RetiroResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CapaIntegracion.integracion.DepositoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CapaIntegracion.integracion.TransferenciaResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CapaIntegracion.integracion.BalanceResponse))]
    public partial class ResponseHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime dateTimeField;
        
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                if ((this.dateTimeField.Equals(value) != true)) {
                    this.dateTimeField = value;
                    this.RaisePropertyChanged("dateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetiroResponse", Namespace="https://capaintegracionbanco.azurewebsites.net")]
    [System.SerializableAttribute()]
    public partial class RetiroResponse : CapaIntegracion.integracion.ResponseHeader {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepositoResponse", Namespace="https://capaintegracionbanco.azurewebsites.net")]
    [System.SerializableAttribute()]
    public partial class DepositoResponse : CapaIntegracion.integracion.ResponseHeader {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferenciaResponse", Namespace="https://capaintegracionbanco.azurewebsites.net")]
    [System.SerializableAttribute()]
    public partial class TransferenciaResponse : CapaIntegracion.integracion.ResponseHeader {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceResponse", Namespace="https://capaintegracionbanco.azurewebsites.net")]
    [System.SerializableAttribute()]
    public partial class BalanceResponse : CapaIntegracion.integracion.ResponseHeader {
        
        private decimal BalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", ConfigurationName="integracion.MainServiceSoap")]
    public interface MainServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (BalanceMethod) of message BalanceMethod does not match the default value (Balance)
        [System.ServiceModel.OperationContractAttribute(Action="https://capaintegracionbanco.azurewebsites.net/BalanceMethod", ReplyAction="*")]
        CapaIntegracion.integracion.BalanceMethod1 Balance(CapaIntegracion.integracion.BalanceMethod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://capaintegracionbanco.azurewebsites.net/BalanceMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.integracion.BalanceMethod1> BalanceAsync(CapaIntegracion.integracion.BalanceMethod request);
        
        // CODEGEN: Generating message contract since the wrapper name (RetiroMethod) of message RetiroMethod does not match the default value (Retiro)
        [System.ServiceModel.OperationContractAttribute(Action="https://capaintegracionbanco.azurewebsites.net/RetiroMethod", ReplyAction="*")]
        CapaIntegracion.integracion.RetiroMethod1 Retiro(CapaIntegracion.integracion.RetiroMethod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://capaintegracionbanco.azurewebsites.net/RetiroMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.integracion.RetiroMethod1> RetiroAsync(CapaIntegracion.integracion.RetiroMethod request);
        
        // CODEGEN: Generating message contract since the wrapper name (DepositoMethod) of message DepositoMethod does not match the default value (Deposito)
        [System.ServiceModel.OperationContractAttribute(Action="https://capaintegracionbanco.azurewebsites.net/DepositoMethod", ReplyAction="*")]
        CapaIntegracion.integracion.DepositoMethod1 Deposito(CapaIntegracion.integracion.DepositoMethod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://capaintegracionbanco.azurewebsites.net/DepositoMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.integracion.DepositoMethod1> DepositoAsync(CapaIntegracion.integracion.DepositoMethod request);
        
        // CODEGEN: Generating message contract since the wrapper name (TransferenciaMethod) of message TransferenciaMethod does not match the default value (Transferencia)
        [System.ServiceModel.OperationContractAttribute(Action="https://capaintegracionbanco.azurewebsites.net/TransferenciaMethod", ReplyAction="*")]
        CapaIntegracion.integracion.TransferenciaMethod1 Transferencia(CapaIntegracion.integracion.TransferenciaMethod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://capaintegracionbanco.azurewebsites.net/TransferenciaMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaIntegracion.integracion.TransferenciaMethod1> TransferenciaAsync(CapaIntegracion.integracion.TransferenciaMethod request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BalanceMethod", WrapperNamespace="https://capaintegracionbanco.azurewebsites.net", IsWrapped=true)]
    public partial class BalanceMethod {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=0)]
        public int noCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=1)]
        public int cedula;
        
        public BalanceMethod() {
        }
        
        public BalanceMethod(int noCuenta, int cedula) {
            this.noCuenta = noCuenta;
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BalanceMethodResponse", WrapperNamespace="https://capaintegracionbanco.azurewebsites.net", IsWrapped=true)]
    public partial class BalanceMethod1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=0)]
        public CapaIntegracion.integracion.BalanceResponse BalanceMethodResult;
        
        public BalanceMethod1() {
        }
        
        public BalanceMethod1(CapaIntegracion.integracion.BalanceResponse BalanceMethodResult) {
            this.BalanceMethodResult = BalanceMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetiroMethod", WrapperNamespace="https://capaintegracionbanco.azurewebsites.net", IsWrapped=true)]
    public partial class RetiroMethod {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=0)]
        public int noCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=1)]
        public decimal Monto;
        
        public RetiroMethod() {
        }
        
        public RetiroMethod(int noCuenta, decimal Monto) {
            this.noCuenta = noCuenta;
            this.Monto = Monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetiroMethodResponse", WrapperNamespace="https://capaintegracionbanco.azurewebsites.net", IsWrapped=true)]
    public partial class RetiroMethod1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=0)]
        public CapaIntegracion.integracion.RetiroResponse RetiroMethodResult;
        
        public RetiroMethod1() {
        }
        
        public RetiroMethod1(CapaIntegracion.integracion.RetiroResponse RetiroMethodResult) {
            this.RetiroMethodResult = RetiroMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepositoMethod", WrapperNamespace="https://capaintegracionbanco.azurewebsites.net", IsWrapped=true)]
    public partial class DepositoMethod {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=0)]
        public int noCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=1)]
        public int cedula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=2)]
        public decimal Monto;
        
        public DepositoMethod() {
        }
        
        public DepositoMethod(int noCuenta, int cedula, decimal Monto) {
            this.noCuenta = noCuenta;
            this.cedula = cedula;
            this.Monto = Monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepositoMethodResponse", WrapperNamespace="https://capaintegracionbanco.azurewebsites.net", IsWrapped=true)]
    public partial class DepositoMethod1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=0)]
        public CapaIntegracion.integracion.DepositoResponse DepositoMethodResult;
        
        public DepositoMethod1() {
        }
        
        public DepositoMethod1(CapaIntegracion.integracion.DepositoResponse DepositoMethodResult) {
            this.DepositoMethodResult = DepositoMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferenciaMethod", WrapperNamespace="https://capaintegracionbanco.azurewebsites.net", IsWrapped=true)]
    public partial class TransferenciaMethod {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=0)]
        public int cuentaOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=1)]
        public int cedula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=2)]
        public decimal monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=3)]
        public string bancoDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=4)]
        public int cuentaDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=5)]
        public int cedulaDestino;
        
        public TransferenciaMethod() {
        }
        
        public TransferenciaMethod(int cuentaOrigen, int cedula, decimal monto, string bancoDestino, int cuentaDestino, int cedulaDestino) {
            this.cuentaOrigen = cuentaOrigen;
            this.cedula = cedula;
            this.monto = monto;
            this.bancoDestino = bancoDestino;
            this.cuentaDestino = cuentaDestino;
            this.cedulaDestino = cedulaDestino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferenciaMethodResponse", WrapperNamespace="https://capaintegracionbanco.azurewebsites.net", IsWrapped=true)]
    public partial class TransferenciaMethod1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://capaintegracionbanco.azurewebsites.net", Order=0)]
        public CapaIntegracion.integracion.TransferenciaResponse TransferenciaMethodResult;
        
        public TransferenciaMethod1() {
        }
        
        public TransferenciaMethod1(CapaIntegracion.integracion.TransferenciaResponse TransferenciaMethodResult) {
            this.TransferenciaMethodResult = TransferenciaMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainServiceSoapChannel : CapaIntegracion.integracion.MainServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceSoapClient : System.ServiceModel.ClientBase<CapaIntegracion.integracion.MainServiceSoap>, CapaIntegracion.integracion.MainServiceSoap {
        
        public MainServiceSoapClient() {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.integracion.BalanceMethod1 CapaIntegracion.integracion.MainServiceSoap.Balance(CapaIntegracion.integracion.BalanceMethod request) {
            return base.Channel.Balance(request);
        }
        
        public CapaIntegracion.integracion.BalanceResponse Balance(int noCuenta, int cedula) {
            CapaIntegracion.integracion.BalanceMethod inValue = new CapaIntegracion.integracion.BalanceMethod();
            inValue.noCuenta = noCuenta;
            inValue.cedula = cedula;
            CapaIntegracion.integracion.BalanceMethod1 retVal = ((CapaIntegracion.integracion.MainServiceSoap)(this)).Balance(inValue);
            return retVal.BalanceMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.integracion.BalanceMethod1> CapaIntegracion.integracion.MainServiceSoap.BalanceAsync(CapaIntegracion.integracion.BalanceMethod request) {
            return base.Channel.BalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.integracion.BalanceMethod1> BalanceAsync(int noCuenta, int cedula) {
            CapaIntegracion.integracion.BalanceMethod inValue = new CapaIntegracion.integracion.BalanceMethod();
            inValue.noCuenta = noCuenta;
            inValue.cedula = cedula;
            return ((CapaIntegracion.integracion.MainServiceSoap)(this)).BalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.integracion.RetiroMethod1 CapaIntegracion.integracion.MainServiceSoap.Retiro(CapaIntegracion.integracion.RetiroMethod request) {
            return base.Channel.Retiro(request);
        }
        
        public CapaIntegracion.integracion.RetiroResponse Retiro(int noCuenta, decimal Monto) {
            CapaIntegracion.integracion.RetiroMethod inValue = new CapaIntegracion.integracion.RetiroMethod();
            inValue.noCuenta = noCuenta;
            inValue.Monto = Monto;
            CapaIntegracion.integracion.RetiroMethod1 retVal = ((CapaIntegracion.integracion.MainServiceSoap)(this)).Retiro(inValue);
            return retVal.RetiroMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.integracion.RetiroMethod1> CapaIntegracion.integracion.MainServiceSoap.RetiroAsync(CapaIntegracion.integracion.RetiroMethod request) {
            return base.Channel.RetiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.integracion.RetiroMethod1> RetiroAsync(int noCuenta, decimal Monto) {
            CapaIntegracion.integracion.RetiroMethod inValue = new CapaIntegracion.integracion.RetiroMethod();
            inValue.noCuenta = noCuenta;
            inValue.Monto = Monto;
            return ((CapaIntegracion.integracion.MainServiceSoap)(this)).RetiroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.integracion.DepositoMethod1 CapaIntegracion.integracion.MainServiceSoap.Deposito(CapaIntegracion.integracion.DepositoMethod request) {
            return base.Channel.Deposito(request);
        }
        
        public CapaIntegracion.integracion.DepositoResponse Deposito(int noCuenta, int cedula, decimal Monto) {
            CapaIntegracion.integracion.DepositoMethod inValue = new CapaIntegracion.integracion.DepositoMethod();
            inValue.noCuenta = noCuenta;
            inValue.cedula = cedula;
            inValue.Monto = Monto;
            CapaIntegracion.integracion.DepositoMethod1 retVal = ((CapaIntegracion.integracion.MainServiceSoap)(this)).Deposito(inValue);
            return retVal.DepositoMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.integracion.DepositoMethod1> CapaIntegracion.integracion.MainServiceSoap.DepositoAsync(CapaIntegracion.integracion.DepositoMethod request) {
            return base.Channel.DepositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.integracion.DepositoMethod1> DepositoAsync(int noCuenta, int cedula, decimal Monto) {
            CapaIntegracion.integracion.DepositoMethod inValue = new CapaIntegracion.integracion.DepositoMethod();
            inValue.noCuenta = noCuenta;
            inValue.cedula = cedula;
            inValue.Monto = Monto;
            return ((CapaIntegracion.integracion.MainServiceSoap)(this)).DepositoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaIntegracion.integracion.TransferenciaMethod1 CapaIntegracion.integracion.MainServiceSoap.Transferencia(CapaIntegracion.integracion.TransferenciaMethod request) {
            return base.Channel.Transferencia(request);
        }
        
        public CapaIntegracion.integracion.TransferenciaResponse Transferencia(int cuentaOrigen, int cedula, decimal monto, string bancoDestino, int cuentaDestino, int cedulaDestino) {
            CapaIntegracion.integracion.TransferenciaMethod inValue = new CapaIntegracion.integracion.TransferenciaMethod();
            inValue.cuentaOrigen = cuentaOrigen;
            inValue.cedula = cedula;
            inValue.monto = monto;
            inValue.bancoDestino = bancoDestino;
            inValue.cuentaDestino = cuentaDestino;
            inValue.cedulaDestino = cedulaDestino;
            CapaIntegracion.integracion.TransferenciaMethod1 retVal = ((CapaIntegracion.integracion.MainServiceSoap)(this)).Transferencia(inValue);
            return retVal.TransferenciaMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaIntegracion.integracion.TransferenciaMethod1> CapaIntegracion.integracion.MainServiceSoap.TransferenciaAsync(CapaIntegracion.integracion.TransferenciaMethod request) {
            return base.Channel.TransferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaIntegracion.integracion.TransferenciaMethod1> TransferenciaAsync(int cuentaOrigen, int cedula, decimal monto, string bancoDestino, int cuentaDestino, int cedulaDestino) {
            CapaIntegracion.integracion.TransferenciaMethod inValue = new CapaIntegracion.integracion.TransferenciaMethod();
            inValue.cuentaOrigen = cuentaOrigen;
            inValue.cedula = cedula;
            inValue.monto = monto;
            inValue.bancoDestino = bancoDestino;
            inValue.cuentaDestino = cuentaDestino;
            inValue.cedulaDestino = cedulaDestino;
            return ((CapaIntegracion.integracion.MainServiceSoap)(this)).TransferenciaAsync(inValue);
        }
    }
}
